using System;
using System.Collections;
using System.Diagnostics;

namespace Project_Euler
{
    class Problem_2
    {
        static void Main(string[] args)
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
            // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            var watch = Stopwatch.StartNew();
            int answer = 0;
            int fnumber = 0;
            ArrayList fnumberTerms = new ArrayList();

            while (fnumber <= 4000000)
            {

            }

        }
    }
}